title: 'ShangDeWu'
author:
  name: 'Yuri Cabrera Reyes'
  email: 'trainer@shangdewu.com'
metadata:
    description: 'Bootstrap 3.0 template by Template-help.com, ported to Grav.'

# Site settings
title: ShangDeWu
email: school@shangdewu.com
description: "New wushu school in Minsk, for all the ages, we apply the most effetive methods and modern technics of wushu, taijiquan and qigong under the tradicional principles and filosofy of this amazing art of China. We are glad to share you our expirence"
adress: Pugachevkaya 10, Minsk
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "https://www.facebook.com/shangdewuschool/"
     icon: facebook.png
  -  url: "https://vk.com/shangdewu"
     icon: vk.png
  -  url: "#"
     icon: twitter.png
  -  url: "#"
     icon: rss.png

social_header:
  -  url: "#"
     icon: fab fa-facebook-f
  -  url: "#"
     icon: facebook-f
  -  url: "#"
     icon: fas fa-facebook-f


copyright:
  line1: Untitl ed
  line2: Design:
  url: http://html5up.net
  url_label: HTML5 UP

logo:
  text1: "Photographer"
  text2: "by HTML5 UP"

# Main Menu
#menu:
#  - text: "submenu"
#    submenu:
#      - text: "info"
#      - text: "profile"
#        link: "#"
#      - text: "news"
#        link: "#"
#        submenu:
#            link: "#"
#          - text: "archive"
#            link: "#"
#    link: "#"
