title: 'ShangDeWu'
author:
  name: 'Yuri Cabrera Reyes'
  email: 'trainer@shangdewu.com'
metadata:
    description: 'Bootstrap 3.0 template by Template-help.com, ported to Grav.'

# Site settings
title: ShangDeWu
email: school@shangdewu.com
description: "New wushu school in Minsk, for all the ages, we apply the most effetive methods and modern technics of wushu, taijiquan and qigong under the tradicional principles and filosofy of this amazing art of China. We are glad to share you our expirence"
adress: Pugachevkaya 10, Minsk
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "https://www.facebook.com/shangdewuschool/"
     icon: fab fa-facebook-f
  -  url: "https://vk.com/shangdewu"
     icon: fab fa-vk
  -  url: "https://www.youtube.com/channel/UCtZfVkDXQhs6H8YxhoDbgbQ"
     icon: fab fa-youtube
