home:
  alias: '/home'

pages:
  theme: photographer
  process:
    markdown: true
    twig: false
  markdown:
    extra: true
  dateformat:
    short: 'd.m.Y'
    long: 'm d, Y'
cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
